version: '3.8'

services:
  backend:
    build:
      context: ../backend-yowpet
      dockerfile: Dockerfile
    ports:
      - "8082:8080" # Puerto fijo para el backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # Puerto fijo para MySQL
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
