version: '3.8'

services:
  backend:
    build:
      context: ../backend-yowpet  # Especificamos la ruta al contexto de construcción (fuera de la carpeta docker)
      dockerfile: Dockerfile       # Aseguramos que Docker use el archivo Dockerfile de la carpeta backend-yowpet
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
