services:
  mysql:
    image: mysql:8.0
    container_name: mysql_yowpet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yowpet
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/yowpet.sql:/docker-entrypoint-initdb.d/01_yowpet.sql
    networks:
      - yowpet-network
    command: --init-file /docker-entrypoint-initdb.d/01_yowpet.sql


networks:
  yowpet-network:

volumes:
  mysql_data: