-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 17:18:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Yowpet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Yowpet` ;

-- -----------------------------------------------------
-- Schema Yowpet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yowpet` DEFAULT CHARACTER SET utf8 ;
USE `Yowpet` ;

-- -----------------------------------------------------
-- Table `Yowpet`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`users` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_firstname` VARCHAR(45) NOT NULL,
  `u_lastname` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(45) NOT NULL,
  `u_password` VARCHAR(45) NOT NULL,
  `u_address` VARCHAR(45) NOT NULL,
  `u_rol` ENUM('admin', 'caregiver', 'user') NOT NULL DEFAULT 'user',
  `u_telephone` VARCHAR(45) NULL,
  `u_gender` ENUM('female', 'male') NOT NULL,
  `u_photo` BLOB NULL,
  `u_state` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  `u_postalcode` VARCHAR(45) NOT NULL,
  `u_birthdate` DATE NULL,
  `u_emergencynum` VARCHAR(45) NOT NULL,
  `u_paymentmethod` ENUM('buzime', 'tarjeta') NULL,
  `u_latitud` DECIMAL(10,7) NULL,
  `u_longitud` DECIMAL(10,7) NULL,
  `u_createdat` DATE NOT NULL,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC) VISIBLE,
  UNIQUE INDEX `u_email_UNIQUE` (`u_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`animal_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`animal_categoria` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`animal_categoria` (
  `ac_id` INT NOT NULL AUTO_INCREMENT,
  `ac_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ac_id`),
  UNIQUE INDEX `ac_id_UNIQUE` (`ac_id` ASC) VISIBLE,
  UNIQUE INDEX `ac_name_UNIQUE` (`ac_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`animals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`animals` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`animals` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(45) NULL,
  `a_categoria` INT NOT NULL,
  PRIMARY KEY (`a_id`),
  INDEX `fk_animals_animal_categoria_idx` (`a_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_animals_animal_categoria`
    FOREIGN KEY (`a_categoria`)
    REFERENCES `Yowpet`.`animal_categoria` (`ac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`places` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`places` (
  `l_id` INT NOT NULL,
  `l_name` VARCHAR(45) NOT NULL,
  `l_address` VARCHAR(45) NOT NULL,
  `l_addresscode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`l_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`cuidadores_work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`cuidadores_work` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`cuidadores_work` (
  `cuidador_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`cuidador_id`, `User_id`),
  INDEX `fk_users_has_users_users2_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`cuidador_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`cuidador_id`)
    REFERENCES `Yowpet`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`User_id`)
    REFERENCES `Yowpet`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`pets` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`pets` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_users_id` INT NOT NULL,
  `p_animal_id` INT NOT NULL,
  `p_name` VARCHAR(45) NULL,
  `p_birthdate` VARCHAR(45) NULL,
  `p_gender` VARCHAR(45) NOT NULL,
  `p_strlization` ENUM('yes', 'no') NULL,
  `p_photo` BLOB NULL,
  INDEX `fk_users_has_animals_animals1_idx` (`p_animal_id` ASC) VISIBLE,
  INDEX `fk_users_has_animals_users1_idx` (`p_users_id` ASC) VISIBLE,
  PRIMARY KEY (`p_id`),
  CONSTRAINT `fk_users_has_animals_users1`
    FOREIGN KEY (`p_users_id`)
    REFERENCES `Yowpet`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_animals_animals1`
    FOREIGN KEY (`p_animal_id`)
    REFERENCES `Yowpet`.`animals` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`alergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`alergies` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`alergies` (
  `al_id` INT NOT NULL AUTO_INCREMENT,
  `al_name` VARCHAR(45) NULL,
  `al_photo` BLOB NULL,
  PRIMARY KEY (`al_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yowpet`.`illness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yowpet`.`illness` ;

CREATE TABLE IF NOT EXISTS `Yowpet`.`illness` (
  `Alergie_id` INT NOT NULL,
  `pet_id` INT NOT NULL,
  PRIMARY KEY (`Alergie_id`, `pet_id`),
  INDEX `fk_Alergies_has_pets_pets1_idx` (`pet_id` ASC) VISIBLE,
  INDEX `fk_Alergies_has_pets_Alergies1_idx` (`Alergie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alergies_has_pets_Alergies1`
    FOREIGN KEY (`Alergie_id`)
    REFERENCES `Yowpet`.`alergies` (`al_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alergies_has_pets_pets1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `Yowpet`.`pets` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;