version: '3.8'

services:
  # Configuration for MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql_yowpet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yowpet
      MYSQL_USER: admin
      MYSQL_PASSWORD: MainTester
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yowpet-network

  # Configuration for MongoDB service (commented out)
  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb_yowpet
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: yowpet
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: MainTester
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - yowpet-network

# Custom network declaration
networks:
  yowpet-network:

# Volumes declaration to save data
volumes:
  mysql_data:
  # mongo_data: # Volume for MongoDB (commented out)